services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
    - 1883:1883
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
    - final_project_iot-net
  react-ui:
    image: final_project_react-ui
    build: ./frontend
    container_name: react-ui
    ports:
    - 8081:80
    depends_on:
    - mqtt-broker
    - subscriber-stack
    restart: unless-stopped
    networks:
    - final_project_iot-net
  publisher:
    image: final_project_publisher
    build: ./backend/publisher
    container_name: publisher
    privileged: true
    devices:
    - /dev/gpiomem:/dev/gpiomem
    - /dev/mem:/dev/mem
    volumes:
    - /proc:/host_proc:ro
    - /sys:/host_sys:ro
    - /boot:/boot:ro
    - /sys/firmware/devicetree/base:/device-tree:ro
    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: '1883'
      PROCFS_MOUNT: /host_proc
      SYSFS_MOUNT: /host_sys
    depends_on:
    - mqtt-broker
    restart: unless-stopped
    networks:
    - final_project_iot-net
  subscriber-stack:
    image: final_project_subscriber_stack
    build: ./backend/subscriber_stack
    container_name: subscriber-stack
    ports:
    - 3000:3000
    - 9090:9090
    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: '1883'
      METRICS_PORT: '8000'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_SERVER_HTTP_ADDR: 0.0.0.0
      GF_SERVER_DOMAIN: 10.183.244.90
      GF_SERVER_ROOT_URL: http://10.183.244.90:3000
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./grafana-data:/var/lib/grafana
    - ./backend/subscriber_stack/sensor_data.txt:/app/sensor_data.txt
    extra_hosts:
      host.docker.internal: host-gateway
    depends_on:
    - mqtt-broker
    restart: unless-stopped
    networks:
    - final_project_iot-net
networks:
  final_project_iot-net:
    driver: bridge
