apiVersion: 1
providers:
  - name: 'default'
    orgId: 1
    folder: ''
    type: file
    disableDelete: false
    updateIntervalSeconds: 10 # Grafana will check for updates every 10 seconds
    options:
      path: /etc/grafana/provisioning/dashboards
